[package]
name = "SmartBeddingRust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.44"
bluer = { version = "0.16", features = ["full"] }
rppal = "0.22.1"
tokio = { version = "1.49.0", features = ["full"] }
futures-util = "0.3"
